window.initIELTS=function(){
const DATA=window.IELTS_DATA;

const SKEY='ielts310-progress-v2';
const WKEY='ielts310-writing-v2';
let state=JSON.parse(localStorage.getItem(SKEY)||'{}');
state.completed=state.completed||{}; state.mistakes=state.mistakes||[]; state.stats=state.stats||{correct:0,total:0};
let currentTopic=0,currentMode='learn',quiz=null,orderItems=[],clozeState=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const escapeHtml=s=>s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function save(){localStorage.setItem(SKEY,JSON.stringify(state));updateProgress()}
function topicKey(i,mode){return `${i}-${mode}`}
function markDone(mode=currentMode){state.completed[topicKey(currentTopic,mode)]=true;save();renderTopicList();showToast('本模式已完成 ✓')}
function addMistake(s,kind){const key=s.id+'-'+kind;if(!state.mistakes.some(x=>x.key===key)){state.mistakes.push({key,id:s.id,kind,topic:currentTopic});save()}}
function updateProgress(){const total=DATA.topics.length*5,done=Object.keys(state.completed).length,p=Math.round(done/total*100);$('#progressPercent').textContent=p+'%';$('#progressRing').style.setProperty('--p',p);$('#progressText').textContent=done?`已完成 ${done} / ${total} 个训练模块。`:'还没有开始。先挑一个主题。';const tdone=['learn','label','order','cloze','write'].filter(m=>state.completed[topicKey(currentTopic,m)]).length;$('#topicDone').textContent=`${tdone}/5`}
function renderTopicList(filter=''){const box=$('#topicList');const q=filter.trim().toLowerCase();box.innerHTML='';DATA.topics.forEach((t,i)=>{if(q&&!(`${t.title_en} ${t.title_zh}`.toLowerCase().includes(q)))return;const d=['learn','label','order','cloze','write'].every(m=>state.completed[topicKey(i,m)]);const b=document.createElement('button');b.className='topic-btn'+(i===currentTopic?' active':'');b.innerHTML=`<span class="n">${String(t.id).padStart(2,'0')}</span><span><strong>${escapeHtml(t.title_en)}${d?'<i class="dot"></i>':''}</strong><small>${escapeHtml(t.title_zh)}</small></span>`;b.onclick=()=>{currentTopic=i;renderAll();if(innerWidth<820)document.querySelector('.workspace').scrollIntoView({behavior:'smooth'})};box.appendChild(b)})}
function setHead(){const t=DATA.topics[currentTopic];$('#topicNumber').textContent='TOPIC '+String(t.id).padStart(2,'0');$('#topicTitle').textContent=t.title_en;$('#topicZh').textContent=t.title_zh;updateProgress()}
const intros={learn:'<b>学习模式：</b>先理解每一句在段落中的功能。点击“隐藏英文”后尝试口头复述，再逐句揭晓。',label:'<b>标签判断：</b>判断当前句子承担什么逻辑功能。选项每题随机排列，做错会进入错题记录。',order:'<b>逻辑排序：</b>10句已经打乱。把它们恢复成一个完整的观点展开链，重点观察因果、让步和回扣。',cloze:'<b>挖空复现：</b>每次随机抽一句并挖掉关键词。先凭语境输入，再核对原句；空格位置每次都会变化。',write:'<b>独立串写：</b>只看10个逻辑动作，自己写成一个完整主体段。写完再展开原始观点链对照，不要逐句翻译。'};
function renderAll(){setHead();renderTopicList($('#topicSearch').value);$('#modeIntro').innerHTML=intros[currentMode];$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.mode===currentMode));({learn:renderLearn,label:startLabel,order:startOrder,cloze:startCloze,write:renderWrite})[currentMode]()}
function renderLearn(){const t=DATA.topics[currentTopic];$('#exercise').innerHTML=`<div class="controls"><button class="btn secondary" id="hideAll">隐藏英文</button><button class="btn light" id="showAll">全部显示</button><button class="btn" id="doneLearn">完成学习</button></div><div class="chain">${t.sentences.map(s=>`<article class="sentence-card"><span class="sid">${s.id}</span><div><span class="label">${escapeHtml(s.label)}</span><p>${escapeHtml(s.text)}</p></div><button class="reveal-btn">隐藏</button></article>`).join('')}</div>`;$$('.reveal-btn').forEach(b=>b.onclick=()=>{const c=b.closest('.sentence-card');c.classList.toggle('hide-text');b.textContent=c.classList.contains('hide-text')?'显示':'隐藏'});$('#hideAll').onclick=()=>{$$('.sentence-card').forEach(c=>c.classList.add('hide-text'));$$('.reveal-btn').forEach(b=>b.textContent='显示')};$('#showAll').onclick=()=>{$$('.sentence-card').forEach(c=>c.classList.remove('hide-text'));$$('.reveal-btn').forEach(b=>b.textContent='隐藏')};$('#doneLearn').onclick=()=>markDone('learn')}
function startLabel(){const t=DATA.topics[currentTopic];quiz={idx:0,score:0,items:shuffle(t.sentences)};renderLabelQ()}
function renderLabelQ(){const s=quiz.items[quiz.idx];const other=shuffle(DATA.labels.filter(x=>x!==s.label)).slice(0,3);const opts=shuffle([s.label,...other]);$('#exercise').innerHTML=`<div class="quiz-card"><div class="quiz-top"><span>第 ${quiz.idx+1} / 10 题</span><span>正确 ${quiz.score}</span></div><p class="prompt">${escapeHtml(s.text)}</p><div class="options">${opts.map(o=>`<button class="option" data-v="${escapeHtml(o)}">${escapeHtml(o)}</button>`).join('')}</div><div class="feedback" id="fb"></div><button class="btn" id="nextQ" style="display:none">下一题</button></div>`;$$('.option').forEach(b=>b.onclick=()=>{if($('#nextQ').style.display==='inline-block')return;state.stats.total++;const ok=b.dataset.v===s.label;if(ok){quiz.score++;state.stats.correct++;b.classList.add('correct');$('#fb').className='feedback good';$('#fb').textContent='正确。继续看这句话如何承接前文。'}else{b.classList.add('wrong');$$('.option').find(x=>x.dataset.v===s.label)?.classList.add('correct');$('#fb').className='feedback bad';$('#fb').innerHTML=`正确标签是 <b>${escapeHtml(s.label)}</b>。这题已加入错题记录。`;addMistake(s,'label')}save();$('#nextQ').style.display='inline-block'});$('#nextQ').onclick=()=>{quiz.idx++;if(quiz.idx>=10){markDone('label');$('#exercise').innerHTML=`<div class="quiz-card"><span class="kicker">RESULT</span><p class="prompt">本轮 ${quiz.score} / 10</p><p>${quiz.score>=8?'逻辑功能识别已经比较稳。':'建议回到学习模式，再看一次标签与句子之间的关系。'}</p><div class="controls"><button class="btn" id="again">再做一轮</button><button class="btn secondary" id="toOrder">进入排序</button></div></div>`;$('#again').onclick=startLabel;$('#toOrder').onclick=()=>switchMode('order')}else renderLabelQ()}}
function startOrder(){orderItems=shuffle(DATA.topics[currentTopic].sentences);renderOrder()}
function renderOrder(){$('#exercise').innerHTML=`<div class="controls"><button class="btn" id="checkOrder">检查顺序</button><button class="btn light" id="reshuffle">重新打乱</button></div><div class="order-list">${orderItems.map((s,i)=>`<div class="order-item"><span class="order-num">${i+1}</span><p>${escapeHtml(s.text)}</p><div class="move"><button data-i="${i}" data-d="-1">↑</button><button data-i="${i}" data-d="1">↓</button></div></div>`).join('')}</div><div id="orderResult"></div>`;$$('.move button').forEach(b=>b.onclick=()=>{let i=+b.dataset.i,j=i+(+b.dataset.d);if(j<0||j>=orderItems.length)return;[orderItems[i],orderItems[j]]=[orderItems[j],orderItems[i]];renderOrder()});$('#reshuffle').onclick=startOrder;$('#checkOrder').onclick=()=>{const target=DATA.topics[currentTopic].sentences;let correct=0;orderItems.forEach((s,i)=>{if(s.id===target[i].id)correct++});const r=$('#orderResult');if(correct===10){r.className='order-result good';r.innerHTML='<b>10/10，顺序完全正确。</b> 你已经恢复了完整的观点链。';markDone('order')}else{r.className='order-result bad';r.innerHTML=`当前有 <b>${correct}/10</b> 个位置正确。继续调整；提示：先找“观点”，最后找“回扣观点”。`}}
}
const stops=new Set('the a an and or but if to of in on at for from with by as is are was were be been being it this that these those they them their there then than can could may might will would should do does did have has had not no more most some many much all both one into through while when where which who whose what how also very only rather such itself already even still'.split(' '));
function pickWords(text){let words=[...text.matchAll(/[A-Za-z][A-Za-z’'-]*/g)].map((m,i)=>({w:m[0],start:m.index,end:m.index+m[0].length})).filter(x=>x.w.length>=5&&!stops.has(x.w.toLowerCase()));let n=Math.min(3,Math.max(2,Math.floor(words.length/5)));return shuffle(words).slice(0,n).sort((a,b)=>a.start-b.start)}
function startCloze(){const t=DATA.topics[currentTopic],s=shuffle(t.sentences)[0],targets=pickWords(s.text);clozeState={s,targets};let out='',last=0;targets.forEach((x,i)=>{out+=escapeHtml(s.text.slice(last,x.start))+`<input class="blank-input" data-i="${i}" autocomplete="off" aria-label="blank ${i+1}">`;last=x.end});out+=escapeHtml(s.text.slice(last));$('#exercise').innerHTML=`<div class="cloze"><div class="quiz-top"><span>${s.id} · ${escapeHtml(s.label)}</span><span>${targets.length} 个空</span></div><div class="cloze-sentence">${out}</div><p class="hint">提示：每空都是原句中的一个关键词；大小写不影响判定。</p><div class="controls"><button class="btn" id="checkCloze">检查</button><button class="btn light" id="showAnswer">显示原句</button><button class="btn secondary" id="newCloze">换一句</button></div><div id="clozeNote"></div></div>`;$('#checkCloze').onclick=()=>{let ok=0;$$('.blank-input').forEach((inp,i)=>{const good=inp.value.trim().toLowerCase()===targets[i].w.toLowerCase();inp.classList.toggle('good',good);inp.classList.toggle('bad',!good);if(good)ok++});if(ok===targets.length){$('#clozeNote').innerHTML='<div class="answer-note">全部正确 ✓</div>';markDone('cloze')}else{$('#clozeNote').innerHTML=`<div class="answer-note">${ok}/${targets.length} 正确。先再想一次，或查看原句。</div>`;addMistake(s,'cloze')}};$('#showAnswer').onclick=()=>{$('#clozeNote').innerHTML=`<div class="answer-note"><b>原句：</b> ${escapeHtml(s.text)}</div>`};$('#newCloze').onclick=startCloze;setTimeout(()=>$('.blank-input')?.focus(),50)}
function renderWrite(){const t=DATA.topics[currentTopic],drafts=JSON.parse(localStorage.getItem(WKEY)||'{}'),key='t'+currentTopic,val=drafts[key]||'';$('#exercise').innerHTML=`<div class="write-box"><div class="cue-grid">${t.sentences.map(s=>`<div class="cue">${escapeHtml(s.label)}</div>`).join('')}</div><textarea id="draft" placeholder="Write one coherent body paragraph here. Aim for 120–180 words...">${escapeHtml(val)}</textarea><div class="write-meta"><span id="wordCount">0 words</span><span>自动保存在本浏览器</span></div><div class="controls"><button class="btn" id="finishWrite">完成串写</button><button class="btn secondary" id="showModel">对照完整观点链</button><button class="btn light" id="clearDraft">清空</button></div><div class="scorebox"><label>TR 展开<select><option>—</option><option>5</option><option>6</option><option>7</option><option>8+</option></select></label><label>CC 连贯<select><option>—</option><option>5</option><option>6</option><option>7</option><option>8+</option></select></label><label>LR 用词<select><option>—</option><option>6</option><option>7</option><option>8+</option></select></label><label>GRA 句法<select><option>—</option><option>6</option><option>7</option><option>8+</option></select></label></div><div id="model" class="model"><h3>完整观点链</h3>${t.sentences.map(s=>`<article class="sentence-card"><span class="sid">${s.id}</span><div><span class="label">${escapeHtml(s.label)}</span><p>${escapeHtml(s.text)}</p></div></article>`).join('')}</div></div>`;const ta=$('#draft');const wc=()=>$('#wordCount').textContent=((ta.value.trim().match(/\b[\w’'-]+\b/g)||[]).length)+' words';wc();ta.oninput=()=>{wc();drafts[key]=ta.value;localStorage.setItem(WKEY,JSON.stringify(drafts))};$('#showModel').onclick=()=>$('#model').classList.toggle('show');$('#finishWrite').onclick=()=>{if((ta.value.trim().match(/\b[\w’'-]+\b/g)||[]).length<70){showToast('先写到至少70词，再标记完成。');return}markDone('write')};$('#clearDraft').onclick=()=>{if(confirm('确定清空本主题草稿？')){ta.value='';drafts[key]='';localStorage.setItem(WKEY,JSON.stringify(drafts));wc()}}}
function switchMode(m){currentMode=m;renderAll();document.querySelector('.workspace').scrollIntoView({behavior:'smooth',block:'start'})}
function showToast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
$$('.tab').forEach(b=>b.onclick=()=>switchMode(b.dataset.mode));$('#topicSearch').oninput=e=>renderTopicList(e.target.value);$('#randomTopic').onclick=()=>{let n;do{n=Math.floor(Math.random()*DATA.topics.length)}while(n===currentTopic);currentTopic=n;renderAll()};$('#focusBtn').onclick=()=>{document.body.classList.toggle('focus');$('#focusBtn').textContent=document.body.classList.contains('focus')?'退出专注':'专注模式'};$('#resetBtn').onclick=()=>{if(confirm('确定清空所有训练进度与错题记录？写作草稿不会删除。')){state={completed:{},mistakes:[],stats:{correct:0,total:0}};save();renderAll()}};
renderAll();

};
